#!/bin/bash
#bot pour clone betty git clone https://github.com/hs-hq/Betty.git dans /root
lancer son intalation ./install.sh
cree un dossier betty avec dedans :

#!/bin/bash
# Simply a wrapper script to keep you from having to use betty-style
# and betty-doc separately on every item.
# Originally by Tim Britton (@wintermanc3r), multiargument added by
# Larry Madeo (@hillmonkey)

BIN_PATH="/usr/local/bin"
BETTY_STYLE="betty-style"
BETTY_DOC="betty-doc"

if [ "$#" = "0" ]; then
    echo "No arguments passed."
    exit 1
fi

for argument in "$@" ; do
    echo -e "\n========== $argument =========="
    ${BIN_PATH}/${BETTY_STYLE} "$argument"
    ${BIN_PATH}/${BETTY_DOC} "$argument"
done


Rendre le dossier fonctionnel chmod a+x betty
et finir par le deplacer dans le directory /bin : mv betty /bin/